### PR TITLE
Babel 6 & Rewrite

### PR DESCRIPTION
**Pull request by thejameskyle**
I had a lot of time to kill on an airplane today and I decided to completely rewrite this plugin.

- Babel 6 (#46)
- Removed internal use of decorators ([re](https://twitter.com/dan_abramov/status/668869347574681600))
- @gaearon I'm not sure what you meant by import shadowing bug ([re](https://twitter.com/dan_abramov/status/668869347574681600))
- Didn't add support for functional components, I think there's more that needs to be discussed separately. I already have a branch that does it in a kinda hacky way ([re](https://twitter.com/dan_abramov/status/668869464054702080))

> Note: This plugin easily could have been upgraded from Babel 5 to Babel 6 without such invasive changes, I just went HAM on this plugin.

### CODE REVIEW

**Comment by thejameskyle** [comment]
```
/.../options-custom-super-classes/actual.js: patterns.find is not a function
```

:cry:

**Comment by gaearon** [comment]
Awesome, thank you!
I'll review as soon as I settle in London.

<3

**Comment by phaistonian** [comment]
So ...are we there yet?:)

**Comment by gaearon** [comment]
This is my last week before starting a new job.
Give me some time away from computers please. :wink:
I'll review soon.

**Comment by phaistonian** [comment]
@gaearon Oh, best of luck in this next adventure.

I read somewhere that you moved to London and, if that's the case, I am so envy.

It's a great place to be, work and live.

Enjoy :)

**Comment by oncletom** [comment]
@phaistonian I confirm London is cool ;-) @gaearon best of luck for your move. if you need any help or tips, let me know :-)

**Comment by thejameskyle** [comment]
@phaistonian @oncletom This is not the best place for conversation, head to twitter

**Comment by joshblack** [comment]
RE: `.find is not a function`, do you want to leverage `Array#find` or just include a polyfill so older versions of node will still work? Noticed it's used [here](https://github.com/thejameskyle/babel-plugin-react-transform/blob/tjk/babel-6/src/index.js#L18) as well.

I know the Relay team just made this change with [their plugin](https://github.com/facebook/relay/commit/53cd4b2acacdf95c22b97027e9e03e2fad598bbd) and wanted to see if this project should do the same as well.

**Comment by thejameskyle** [comment]
Yeah, I need to do that

**Comment by thebigredgeek** [comment]
Bump?  Any update on this?  Need it badly

**Comment by gaearon** [comment]
>Need it badly

Please help to add support for functional components on top of this. The work was started in #34 but it would need to be rewritten in accordance with these changes. It's fine if the only scenario we support is `let`/`const` top-level binding. You can also start working on changing the README to match this rewrite.

**I wish I could work on this right now but I just can't.** There's no amount of "+1"s that can change this. When I get some free time from my new job, I will definitely finish this, but I can't give you any exact date. Until README is updated and support for functional components is added, I can't release this yet.

**Comment by amoshche** [comment]
Got the gaeron/react-transform-boilerplate#64 - does not work
ERROR in ./src/App.js
Module build failed: TypeError: C:/home/Alexey/work/js/react-transform-boilerplate/src/App.js: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement"] but instead got "ClassDeclaration"
    at validate (C:\home\Alexey\work\js\react-transform-boilerplate\node_modules\babel-types\lib\definitions\index.js:98:13)
...
    at wrapComponent (C:\home\Alexey\work\js\react-transform-boilerplate\node_modules\babel-plugin-react-transform\lib\index.js:53:14)

**Comment by justingreenberg** [comment]
@amoshche the build error is a result of [a known issue with `babel-eslint`](https://github.com/babel/babel-eslint/issues/218) (`acorn-to-esprima` not converting getters/setters) and is unrelated to `babel-plugin-react-transform` or this PR

**Comment by STRML** [comment]
Work is continuing at https://github.com/thejameskyle/babel-plugin-react-transform/pull/1 and this PR should be mergeable for a pre-release as I know a lot of projects are waiting on this to move to Babel 6. @gaearon, after @thejameskyle merges, how do you feel about us opening a subsequent issue to track stateless functional components and having you publish this as a `2.0.0-prerelease`?

**Comment by thejameskyle** [comment]
@gaearon I'm also in favor of pushing functional components. There's no semantic way of making them work, only enforceable by having certain opinions about how they should be written, as such they should be discussed at greater length separate from this issue.

**Comment by sahat** [comment]
A bit late to the party, but @thejameskyle was the rewrite really necessary when doing the bare minimum work to support Babel 6 could have been sufficient? Even though Dan wrote this library, doing a code review for such massive pull request isn't trivial or time efficient, which will only delay the PR merge.

Anyway, thanks for your work, hot reloading is not that critical for me, so I am going to wait until the new version of babel-plugin-react-transform is released.

**Comment by thejameskyle** [comment]
> was the rewrite really necessary when doing the bare minimum work to support Babel 6 could have been sufficient?

@sahat I originally planned to do just that, but reading through the codebase I realized it needed a lot of love as it was doing a number of things that broke convention or were just straight up hacks. I had 5 hours on a plane to do it so I did.

**Comment by STRML** [comment]
Looks like green light everywhere except Node 0.10, where we're hitting a missing Symbol dependency. Could root it out, although IMO it seems reasonable to just drop 0.10 support.

**Comment by nkbt** [comment]
> @STRML Looks like green light everywhere except Node 0.10, where we're hitting a missing Symbol dependency. Could root it out, although IMO it seems reasonable to just drop 0.10 support.

That is OK, actually. I've got several dev deps that require modern Node (Symbol, Promise, etc) and use them successfully on node 0.10. With `babel-runtime` of course. Not for production, but as part of build process that seems quite reasonable.

Deprecating 0.10 support should mean major version bump though...

**Comment by thejameskyle** [comment]
> Deprecating 0.10 support should mean major version bump though...

This is already going to have to be a major bump

**Comment by gaearon** [comment]
>@sahat I originally planned to do just that, but reading through the codebase I realized it needed a lot of love as it was doing a number of things that broke convention or were just straight up hacks. I had 5 hours on a plane to do it so I did.

And be sure this is very appreciated. :+1:

**Comment by moretti** [comment]
Thanks @thejameskyle for the excellent work. 

I played with dev branch earlier this morning and I got the following error when I tried to transpile a basic component:

```
TypeError: src/index.js: Property declaration of ExportDefaultDeclaration expected node to be of a type ["FunctionDeclaration","ClassDeclaration","Expression"] but instead got "VariableDeclaration"
    at Object.validate (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-types/lib/definitions/index.js:98:13)
    at Object.validate (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-types/lib/index.js:266:9)
    at NodePath._replaceWith (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:201:7)
    at NodePath.replaceWith (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:179:8)
    at Object.Class (project/node_modules/babel-plugin-react-transform/lib/index.js:99:12)
    at NodePath._call (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (project/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:19)
```
I created a small repo to replicate the issue: 
https://github.com/moretti/react-transform-babel6-rewrite-issue

**Comment by justingreenberg** [comment]
hey @moretti this behavior is caused by interop issues between es2015 modules and commonjs and is unrelated to this plugin. es2015 `default exports` must be declared in upstream modules to work correctly with [babel-plugin-transform-es2015-modules-commonjs](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-commonjs) (to demonstrate issue, remove `default` from the export statement in index.js and it should transpile correctly)

 * you can use es2015 default exports from another file and `import` to downstream module (index.js)
 * to create default export behavior from within an entry module, you can use commonjs syntax (assign class declaration directly to exports ie. `module.exports = HelloWorld`)

this is my understanding, @thejameskyle will have to confirm

**Comment by thejameskyle** [comment]
Nah it's totally valid to do:

```js
export default class Foo extends React.Component {}
```

and expect it to work, I just never handled that case so right now it's trying to do:

```js
export default const Foo = ...
```

Which is invalid. Working on fixing it

**Comment by thejameskyle** [comment]
I know what the fix here is, but we are having some problems in Babel around `ExportDefaultDeclaration` validating nodes incorrectly. This isn't going to work until we fix it.

**Comment by thejameskyle** [comment]
I take that back, thanks to @hzoo I was able to get this working

**Comment by thejameskyle** [comment]
Okay, so since this is one of the most used Babel plugins outside of the project itself and is currently blocking a lot of users from the React community from using Babel 6, I've asked @gaearon to add me to the project so that I could publish everything and fix things as issues arise.

The plan is going to be to publish a prerelease version this evening and ask everyone to test things out, then depending on the issues that arise we'll publish the final major version sometime in the next few days.

I'm going to merge now, if you notice anything that needs updating in the repo please make a PR. I'll also go through it again myself this evening.

Also: I just removed the `Symbol` to support Node v0.10.

**Comment by davezuko** [comment]
Hooray! Thanks so much @thejameskyle and @gaearon!

**Comment by Apercu** [comment]
:heart: @thejameskyle @gaearon

**Comment by jhen0409** [comment]
:+1: :+1: :+1:

**Comment by STRML** [comment]
Nice work guys.

**Comment by bpierre** [comment]
Thank you!

**Comment by chentsulin** [comment]
Awesome :+1:

**Comment by weblancaster** [comment]
Great work @thejameskyle

**Comment by leandrooriente** [comment]
Great!

**Comment by bluedaniel** [comment]
Thanks :smile:

**Comment by Bertg** [comment]
Extatic

**Comment by mathieumg** [comment]
:tada:

**Comment by weblancaster** [comment]
It just need to be released though haha.

**Comment by bjrmatos** [comment]
@thejameskyle thnk you so much for adding support for node 0.10.x :)

**Comment by lusentis** [comment]
Thank you!

**Comment by trueter** [comment]
Much appreciated!

**Comment by r-park** [comment]
Thanks :smiley:

**Comment by LeoLeBras** [comment]
Thank you !!! :)

**Comment by Moeriki** [comment]
Thanks all! This is the most amazing feature to have!

**Comment by carloscuatin** [comment]
thanks :) !

**Comment by thejameskyle** [comment]
Thanks for the thanks-es, but these emails are driving me crazy

**Comment by thejameskyle** [comment]
Just published `babel-plugin-react-transform@2.0.0-beta1` please check it out in your projects and make sure it works.

For an example of how to set it up in Babel 6 check out this repo: https://github.com/thejameskyle/babel-setup-react-transform

**Comment by thejameskyle** [comment]
**Note:** This prerelease is not tagged as latest, you will have to run either:

```sh
$ npm install --save-dev babel-plugin-react-transform@beta
```

or

```sh
$ npm install --save-dev babel-plugin-react-transform@2.0.0-beta1
```

**Pull request merged**
