### PR TITLE
Move to Babel 6 (WIP)

### PR DESCRIPTION
**Pull request by chicoxyzzy**
# Work In Progress

see #46 for previous discussion

Checklist
- [x] migrate build step to Babel 6
- [x] update tests
- [ ] fix `Program.exit`

### CODE REVIEW

**Comment by nelix** [comment]
Seems like the fixtures just need updating, is this something that is done manually? Seems like a really fragile set of tests but I guess I am not sure what else you would do.

What's happening with pragram.exit?

**Comment by kainoa21** [comment]
Looking into updating the expected test file for modern.  For the most part, the changes mirror those from classic with one exception.  The actual output is no longer producing the code that calls `_wrapComponent`.  I am fairly new to both babel and this react-transform plugin, but the call to `_wrapComponent` seems necessary for functionality.   If that is a true statement, does anyone know what changes are necessary in the plugin itself to make this work?

### Actual
```javascript
var LikelyComponent = (function () {
  function LikelyComponent() {
    _classCallCheck(this, LikelyComponent);
  }

  _createClass(LikelyComponent, [{
    key: "render",
    value: function render() {}
  }]);

  return LikelyComponent;
})();
```

### Expected
```javascript
var LikelyComponent = (function () {
  function LikelyComponent() {
    _classCallCheck(this, _LikelyComponent);
  }

  _createClass(LikelyComponent, [{
    key: "render",
    value: function render() {}
  }]);

  var _LikelyComponent = LikelyComponent;
  LikelyComponent = _wrapComponent("_$LikelyComponent")(LikelyComponent) || LikelyComponent;
  return LikelyComponent;
})();
```

**Comment by justingreenberg** [comment]
@chicoxyzzy @danderu thanks for tackling this! can you describe the outstanding issue with `program.exit`? 6fcecf7 seems to be working on my end...

**Comment by danderu** [comment]
@justingreenberg you are welcome! I don't know what does the "`program.exit`" issue means. It seems to be ok for me.

**Comment by kainoa21** [comment]
@danderu were you able to verify that the current code that is being output is functionally correct?  See my previous comment about `wrapComponent` not being called for the modern test

**Comment by kainoa21** [comment]
Pursuant to my previous comments, I am pretty sure that the decorators added in the `ClassExpression` transformation are not being handled correctly for the modern test case.  It is possible that this is an issue with the .babelrc missing needed plugins or with Babel 6.  See https://phabricator.babeljs.io/T2700 and https://phabricator.babeljs.io/T2648

**Comment by TaopaiC** [comment]
Hi @kainoa21 , I didn't put transform-decorator plugin in .babelrc since decorator in babel is not supported yet. see https://github.com/gaearon/babel-plugin-react-transform/issues/46#issuecomment-154833064 and https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-decorators/src/index.js#L83 .

**Comment by kainoa21** [comment]
@TaopaiC, then in order for this to work I think we will need to refactor the `ClassExpression` transform to not use decorators.

**Comment by danderu** [comment]
@kainoa21 I'll be available to check what you are pointing out tomorrow, thanks! :)

**Comment by danmartinez101** [comment]
Heh, I finally caught up to where you all are and arrived at the same place so that is good :)

**Comment by liorkesos** [comment]
Is anyone still working on this?
does anybody found any different successful method of hot reloading react with babel6?

**Comment by rmccue** [comment]
@liorkesos Hot reloading with Babel 6 should work using this branch, I'm using it locally successfully. You'll need to pull this branch down and run `npm build`

**Comment by chicoxyzzy** [comment]
I don't sure this branch works proper. Can someone confirm it works ok?

**Comment by justingreenberg** [comment]
@liorkesos @chicoxyzzy tests are passing and transforms are working on gaearon/react-transform-boilerplate#64 using this branch and babel 6 (w/ hot module reloading, error catching)

**Comment by rmccue** [comment]
> Can someone else confirm it works ok?

Yep, working for me locally with a similar config to @justingreenberg. Assuming this just needs the `Program.exit` change before it's merged?

(I'd help out, but still pretty new to React/Babel, so not sure I can help productively there.)

**Comment by gaearon** [comment]
Thank you for the effort! Closing in favor of #50 from one of Babel's creators. :stuck_out_tongue:

**Comment by chicoxyzzy** [comment]
cool!

**Pull request closed without merging**
