### PR TITLE
Doesn't work with non valid identifier display name

### PR DESCRIPTION
**Pull request by lowik**
Typically if you use dashed js file name

Line 22: Unexpected token -
You may need an appropriate loader to handle this file type.
|
| var _components = {
|       basic-layout: {
|               displayName: 'basic-layout'
|       }

Simple workaround: define a valid identifier displayName in your React component
(https://mathiasbynens.be/notes/javascript-identifiers)

PR: replace identifier key by string literal key

### CODE REVIEW

**Comment by thejameskyle** [comment]
This should only be a string literal if it is not a valid identifier, you can use: `t.isValidIdentifier(name)` to determine that.

**Comment by lowik** [comment]
Great thanks, I will update the PR

**Comment by Nickman87** [comment]
Same issue as mine: https://github.com/gaearon/babel-plugin-react-transform/pull/58
This solution is more elegant though :)

**Comment by thejameskyle** [comment]
Manually merged as https://github.com/gaearon/babel-plugin-react-transform/commit/9c7d88a3b8395ae7d25f7fc575d415e7395335b2

**Pull request closed without merging**
