### PR TITLE
detect and wrap transpiled class components

### PR DESCRIPTION
**Pull request by jwbay**
This allows projects written in [Typescript](https://github.com/Microsoft/TypeScript/) to leverage this plugin for their ES6 class React components without requiring Typescript's compilation target to be set to ES6.

In theory it should be straightforward to have TS target ES6 and let Babel take over for ES3/5, but there are gotchas, especially around module handling. Ironically enough, `transform-es2015-modules-commonjs` is the one Babel plugin required along with this one since it injects ES6 modules, but it doesn't raise any of the same issues.

The constraints to recognize this new entity are fairly tight and bail as early as possible while traversing.

### CODE REVIEW

**Comment by gaearon** [comment]
I'd be happy to support this if we find a way to also make it work for CoffeeScript with shared code.

**Comment by jwbay** [comment]
Seems quite doable. I'll give it a shot soon.

**Comment by jwbay** [comment]
CoffeeScript is now along for the ride. It just has a slightly different "extends" clause, everything else we care about is the same.

Also added support for super classes as a qualifier.

**Comment by gaearon** [comment]
Hey, sorry about the churn. Would you mind updating the PR to merge cleanly?

**Comment by jwbay** [comment]
No problem, updated. Also adjusted the wrap qualifiers per #86.

**Comment by gaearon** [comment]
Ugh, I’m sorry I put you though this! After a while I became convinced this project isn’t really going in the right direction so I created [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).

The link in question shows Babel configuration, but you can remove `react-hot-loader/babel` from .babelrc and instead add `react-hot-loader/webpack` to loaders. Even with Babel, all top level variable declarations should be registered correctly as components so this is no longer necessary. The Webpack loader just detects `module.exports` which is also good enough for many cases.

Cheers!

**Pull request closed without merging**
